# Generated by Django 4.2.4 on 2023-09-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierGenerale',
            fields=[
                ('Idcalendrier', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('DateCreation', models.DateField(null=True)),
                ('Commentaire', models.TextField(null=True)),
            ],
            options={
                'db_table': 'calendrierGenerale',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('IdHoraire', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateField(null=True)),
                ('HDebut', models.TimeField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('HFin', models.TimeField(null=True)),
                ('Commentaire', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Horaire',
            },
        ),
        migrations.CreateModel(
            name='Personnelles',
            fields=[
                ('IdPersonnel', models.AutoField(primary_key=True, serialize=False)),
                ('Matricule', models.CharField(max_length=25, null=True)),
                ('Cin', models.CharField(max_length=25, null=True)),
                ('Nom', models.CharField(max_length=25, null=True)),
                ('Prenom', models.CharField(max_length=25, null=True)),
                ('TelephonePersonnel', models.CharField(max_length=25, null=True)),
                ('TelephoneProfessionel', models.CharField(max_length=25, null=True)),
                ('EmailPersonnel', models.EmailField(max_length=100, null=True)),
                ('Genre', models.CharField(max_length=25, null=True)),
                ('DateNaissance', models.DateField(null=True)),
                ('LieuNaissance', models.CharField(max_length=50, null=True)),
                ('NbrEnfant', models.IntegerField(null=True)),
                ('Photo', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('MotDePasse', models.CharField(max_length=255, null=True)),
                ('DateAffiliation', models.DateField(null=True)),
                ('DateDepart', models.DateField(null=True)),
                ('SoldeConge', models.FloatField(null=True)),
                ('SoldeRecuperation', models.FloatField(null=True)),
                ('RestAnneeDerniere', models.FloatField(null=True)),
                ('SalaireMensuel', models.FloatField(null=True)),
                ('SalaireHoraire', models.FloatField(null=True)),
                ('IdFromPointeurse', models.IntegerField(null=True)),
                ('CardNumber', models.IntegerField(null=True)),
                ('Statut', models.CharField(max_length=55, null=True)),
            ],
            options={
                'db_table': 'Personnelles',
            },
        ),
        migrations.CreateModel(
            name='PRole',
            fields=[
                ('IdRole', models.AutoField(primary_key=True, serialize=False)),
                ('NameRole', models.CharField(max_length=100, null=True)),
                ('DescriptionRole', models.CharField(max_length=300, null=True)),
                ('Statut', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'P_Role',
            },
        ),
        migrations.CreateModel(
            name='PService',
            fields=[
                ('IdService', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionService', models.CharField(max_length=300, null=True)),
                ('CodeService', models.IntegerField(null=True)),
                ('Statut', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'P_Service',
            },
        ),
        migrations.CreateModel(
            name='PSociete',
            fields=[
                ('IdSociete', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionSociete', models.CharField(max_length=300, null=True)),
                ('Localisation', models.CharField(max_length=300, null=True)),
                ('Telephone', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('RC', models.CharField(max_length=300, null=True)),
                ('CodeSociete', models.IntegerField(null=True)),
                ('Statut', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'P_Societe',
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('IdTypeAbsence', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionAbsence', models.CharField(max_length=300, null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('Statut', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'TypeAbsence',
            },
        ),
        migrations.CreateModel(
            name='TypeAttestation',
            fields=[
                ('IdTypeAttestation', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionAttestation', models.CharField(max_length=300, null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('Statut', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'TypeAttestation',
            },
        ),
        migrations.CreateModel(
            name='PPoste',
            fields=[
                ('IdPoste', models.AutoField(primary_key=True, serialize=False)),
                ('DescriptionPoste', models.CharField(max_length=300, null=True)),
                ('CodePoste', models.IntegerField(null=True)),
                ('Statut', models.CharField(max_length=10, null=True)),
                ('IdService', models.ForeignKey(db_column='IdService', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.pservice')),
            ],
            options={
                'db_table': 'P_Poste',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('IdPointage', models.AutoField(primary_key=True, serialize=False)),
                ('DateEntre', models.DateField(null=True)),
                ('HE', models.BigIntegerField(null=True)),
                ('DateSoti', models.DateField(null=True)),
                ('HS', models.BigIntegerField(null=True)),
                ('DateExtraction', models.DateField(null=True)),
                ('OutilPointageE', models.CharField(max_length=50, null=True)),
                ('OutilPointageS', models.CharField(max_length=50, null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('IdPersonnel', models.ForeignKey(db_column='IdPersonnel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.personnelles')),
            ],
            options={
                'db_table': 'Pointage',
            },
        ),
        migrations.CreateModel(
            name='PlanDeRoulement',
            fields=[
                ('IdPlanDeRoulement', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('DateCreation', models.DateField(null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('JTravail', models.CharField(max_length=30, null=True)),
                ('JRepos', models.CharField(max_length=30, null=True)),
                ('JReposTravaile', models.CharField(max_length=30, null=True)),
                ('JFerieTravaille', models.CharField(max_length=30, null=True)),
                ('Modification', models.CharField(max_length=30, null=True)),
                ('DateModification', models.DateField(null=True)),
                ('IdHoraire', models.ForeignKey(db_column='IdHoraire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.horaire')),
                ('IdPersonneModifier', models.ForeignKey(db_column='IdPersonneModifier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_by', to='rhcemos.personnelles')),
                ('IdPersonnelCreePar', models.ForeignKey(db_column='IdPersonnelCreePar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_created_by', to='rhcemos.personnelles')),
                ('IdPersonnelCreePour', models.ForeignKey(db_column='IdPersonnelCreePour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_created_for', to='rhcemos.personnelles')),
            ],
            options={
                'db_table': 'PlanDeRoulement',
            },
        ),
        migrations.AddField(
            model_name='personnelles',
            name='IdPoste',
            field=models.ForeignKey(db_column='IdPoste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.pposte'),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='IdRole',
            field=models.ForeignKey(db_column='IdRole', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.prole'),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='IdSociete',
            field=models.ForeignKey(db_column='IdSociete', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.psociete'),
        ),
        migrations.CreateModel(
            name='ErreurPointage',
            fields=[
                ('IdErreurPointage', models.AutoField(primary_key=True, serialize=False)),
                ('DateInsertion', models.DateField(null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('IdPointage', models.ForeignKey(db_column='IdPointage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.pointage')),
            ],
            options={
                'db_table': 'ErreurPointage',
            },
        ),
        migrations.CreateModel(
            name='DemandeHS',
            fields=[
                ('IdDemandeHS', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebutHS', models.DateField(null=True)),
                ('HDebut', models.TimeField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('HFin', models.TimeField(null=True)),
                ('TauxHoraire', models.FloatField(null=True)),
                ('ValidationChef1', models.CharField(max_length=30, null=True)),
                ('ValidationChef2', models.CharField(max_length=30, null=True)),
                ('ValidationRH', models.CharField(max_length=30, null=True)),
                ('DateSaisi', models.DateField(null=True)),
                ('DateDernierModification', models.DateField(null=True)),
                ('Commentaire', models.TextField(null=True)),
                ('IdPersonnelCreePar', models.ForeignKey(db_column='IdPersonnelCreePar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='rhcemos.personnelles')),
                ('IdPersonnelCreePour', models.ForeignKey(db_column='IdPersonnelCreePour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_for', to='rhcemos.personnelles')),
            ],
            options={
                'db_table': 'DemandeHS',
            },
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('IdDemandeAttestation', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreation', models.DateField(null=True)),
                ('ValidationRH', models.CharField(max_length=30, null=True)),
                ('IdPersonnel', models.ForeignKey(db_column='IdPersonnel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.personnelles')),
                ('IdTypeAttestation', models.ForeignKey(db_column='IdTypeAttestation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.typeattestation')),
            ],
            options={
                'db_table': 'DemandeAttestation',
            },
        ),
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('IdDemandeAbsence', models.AutoField(primary_key=True, serialize=False)),
                ('DateDebut', models.DateField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('DureAbsence', models.FloatField(null=True)),
                ('MotifAbsence', models.TextField(null=True)),
                ('TelAbsence', models.CharField(max_length=30, null=True)),
                ('MailAbsence', models.CharField(max_length=250, null=True)),
                ('ValidationChef1', models.CharField(max_length=30, null=True)),
                ('ValidationChef2', models.CharField(max_length=30, null=True)),
                ('ValidationRH', models.CharField(max_length=30, null=True)),
                ('DateSaisi', models.DateField(null=True)),
                ('DateDernierModification', models.DateField(null=True)),
                ('PJDemandeAbsence', models.TextField(null=True)),
                ('IdPersonnel', models.ForeignKey(db_column='IdPersonnel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.personnelles')),
                ('IdTypeAbsence', models.ForeignKey(db_column='IdTypeAbsence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcemos.typeabsence')),
            ],
            options={
                'db_table': 'DemandeAbsence',
            },
        ),
    ]
